### PR TITLE
Consistent naming of integration ConfigMap labels

### PR DESCRIPTION
**Pull request by rhuss**
and inroduced enums to make it slightly more typesafe (and baked in the
comment 'mandatory' into the enum, not sure whether its needed).

Not even sure whether this is needed as the backend probably moves to a DB anyway.

Feel free to reject this PR :)

### CODE REVIEW

**Comment by KurtStam** [comment]
Yeah not sure yet if we're going to keep this code so let's wait and see.

**Comment by chirino** [comment]
is this PR still valid?

**Comment by chirino** [comment]
@KurtStam any updates?

**Comment by KurtStam** [comment]
I think we can close?

**Comment by KurtStam** [comment]
Patch is out of date

**Pull request closed without merging**
