### PR TITLE
Add description field to Integration

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by jimmidyson** [comment]
Self-[merge]ing - this isn't controversial!

**Comment by rhuss** [comment]
ha! And what's with the IntegrationTemplate's name ? https://github.com/redhat-ipaas/ipaas-rest/pull/101/commits/c1c94033058d615c0854fdd48fd7bee3c4c6aab3#diff-32e5078310f36ddb426e779c08164f5cR213 ;-)

**Comment by jimmidyson** [comment]
@rhuss There's a load of data that isn't used in there, that's just one example of many...

**Comment by rhuss** [comment]
@jimmidyson Sorry, should keep my mouth shut when people are hard at work .... :) no disturbance from my side anymore.

Let me know when you need help, will be up early tomorrow.

**Pull request merged**
