### PR TITLE
Remove position property from Connector

### LINKED ISSUE #278: Getting HTTP 500 fetching some connections
```
{
  "timestamp": 1491333845659,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.jboss.resteasy.spi.UnhandledException",
  "message": "java.lang.NullPointerException: position",
  "path": "\/api\/v1\/connections\/7"
}
```

Related to https://github.com/redhat-ipaas/ipaas-ui/issues/364

### LINKED ISSUE #281: Getting HTTP 500 fetching any kind of list
Just started happening this afternoon...

```
{
  "timestamp": 1491504481876,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.jboss.resteasy.spi.UnhandledException",
  "message": "com.redhat.ipaas.core.IPaasServerException: An error has occurred.",
  "path": "\/api\/v1\/connections"
}
```

### PR DESCRIPTION
**Pull request by jimmidyson**
As discussed on IRC.

Fixes #278, fixes #281

### CODE REVIEW

**Comment by jimmidyson** [comment]
Yeah, screwed up any kind of listing/get by throwing NPE if not set. Could make it optional, but it's not actually needed or indeed makes sense for Connections, should be more for Actions, but for now let's remove and revisit later to get staging back up and running again.

@gashcrumb Put @KurtStam's mind at ease that Connection.position not used in UI please :)

**Comment by gashcrumb** [comment]
@KurtStam yeah, it's not currently used in the UI, it was ages ago in the old version that talked to forge, but that code's long gone :-)

**Comment by jimmidyson** [comment]
Anyone care to approve review? Or not... Either way, would like to move this forward quickly to try to fix staging.

**Comment by jimmidyson** [comment]
Self-merging after above discussion, taking that as approval :)

**Pull request merged**
