### PR TITLE
Add a CacheForFilter and @CacheFor annotation to do annotation based http response cache configuration, it defaults to disable caching when not configured.

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by jimmidyson** [comment]
Do we want browsers/clients to cache responses from our REST API? Not sure we do.

**Comment by chirino** [comment]
@jimmidyson exactly.. we generally don't want them to cache the responses.  This filter disables caching by default unless you explicitly annotate the class/method with the '@CacheFor' annotation.  

Without this change we never set the Cache-Control header which let browsers like IE cache responses which caused problems.

**Comment by KurtStam** [comment]
@chirino the things we do for IE.. @dsimansk do we have a list of browsers we have to support and if so what is it? BTW are we working towards running the automated tests on each of those?

**Comment by jimmidyson** [comment]
@chirino Really?!?! That's awful!

**Comment by chirino** [comment]
retest this please

**Comment by jimmidyson** [comment]
[merge]

**Pull request merged**
