### PR TITLE
Need more sample integrations in various states #318

### PR DESCRIPTION
**Pull request by KurtStam**
A few more integrations that are fixed in various states just so the view can be further developed

### CODE REVIEW

**Comment by KurtStam** [comment]
1. For as far as I understand it you can't set the desiredState to Pending, but the currentState can be pending while things are getting deployed etc.

2. I've added another example with a Deleted states.

**Comment by rhuss** [comment]
> Pending is a state? When was this introduced, or maybe I need to regen our model then?

@gashcrumb The state "Pending" is used when a OpenShift build has started but the application is not yet deployed (its determined with the number of pods running. 0: pending, 1: activated). What I currently miss is an "Error" state, e.g. when the build fails or the pod canot be deployed (as it is the case at the moment because of some service account related issues).

However, when we introduce an "Error" state we have to think also how the user can deal with it:

* Showing some logs
* Restarting the step causing the error
* Deleting the integration
....

Otherwise its more frustrating than having an ever lasting "Pending" state, because there is still hope ;-)

**Comment by rhuss** [comment]
@gashcrumb The current states are

```java
enum Status { Draft, Pending, Activated, Deactivated, Deleted};
```

**Comment by gashcrumb** [comment]
@rhuss awesome, thanks for clarifying.  This is definitely a case where it would have been good to know this was added when it was added so we can run our swagger generator client-side.

@kahboom I'll run the generator and get this updated, we'll have to adjust the views, I guess now the spinner should just show up when the `integration.currentStatus` is at `Pending` state and we can get rid of the current logic that shows the spinner when there's a mismatch between `desiredStatus` and `currentStatus`

**Comment by kahboom** [comment]
> Otherwise its more frustrating than having an ever lasting "Pending" state, because there is still hope ;-)

lol! This cracked me up. I think eventually an "Error" state would be convenient, but I agree that it's better to wait and do it properly. Thank you @rhuss and @KurtStam !

**Pull request merged**
