### PR TITLE
[WIP] Keycloak integration

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by jimmidyson** [comment]
This is ready for review when you get a chance. I need to add some docs - will do tomorrow. The integration tests start up a local keycloak server with imported realm ready configured for bearer token authentication.

Currently this allows any authenticated user to access the REST API. We need to think about authorization in future iterations.

Please don't merge yet though, have to fix up the console first so we don't break staging - we need to have some acceptance tests some time too...

**Comment by KurtStam** [comment]
Looks great, some comments:

- The runtime/pom.xml is getting pretty long, is there any way we can split the keycloak stuff out into a submodule? It's unclear to me if a keycloak server is started during the integration test only or always.
- It's great that we have tests for this stuff, very nice :)
- Can the realm.json still be used to run in a remote keycloak server? I see some of the realm-client-config in java.
- It still supports token as well as form authentication on the REST API right?
- RE authorization, we will need to add roles in keycloak, then we can use those in our apps. 
- As you already mentioned this needs documentation.

**Comment by jimmidyson** [comment]
Thanks for the review @KurtStam. To answer your questions:

>The runtime/pom.xml is getting pretty long, is there any way we can split the keycloak stuff out into a submodule? It's unclear to me if a keycloak server is started during the integration test only or always.

Right now I can't think of a nice way to split that out. I think once we get some further integration tests in place, hopefully via @iocanel's system test runner, we can trim this pom down, but I think it's necessary for at least a little while.

> Can the realm.json still be used to run in a remote keycloak server? I see some of the realm-client-config in java.

Yes the realm.json is usable, but needs review for production purposes. It is minimal, but usable. For prod/staging deployment, I have figured out a way to bootstrap required realm.

> It still supports token as well as form authentication on the REST API right?

The REST API only bearer token authentication. This is easy for the browser client to sort out, but we will need a story going forward for non-browser clients. Not a problem for now though.

> RE authorization, we will need to add roles in keycloak, then we can use those in our apps.

Right. We need to look at how we use keycloak, especially when we're talking about multitenancy in future.

> As you already mentioned this needs documentation.

Working on it :) Definitely needed before merge.

**Comment by jimmidyson** [comment]
Added some docs - this is now ready, just need to ensure it all works nicely with the UI.

Don't worry about the appveyor failure - that's a Windows thing that I need @gashcrumb's help with if he has some time to try out my start scripts.

**Comment by gashcrumb** [comment]
@jimmidyson just let me know what you need me to do...

**Comment by jimmidyson** [comment]
@gashcrumb You legend! Can you check out this PR branch locally and try to run `mvn clean install`? Just want to see if the keycloak stuff starts up properly for integrations tests.

Plus running `start-with-keycloak.bat` to see if that starts up properly for you if you have time?

**Comment by gashcrumb** [comment]
@jimmidyson https://gist.github.com/3e918ec07d2d29004613ee02c4b9e789

**Comment by gashcrumb** [comment]
Wonder if you should use `standalone.ps1` instead, most Windows folks these days should be using powershell, not `cmd.exe`.  At least the cool ones :-)

**Comment by gashcrumb** [comment]
BTW, can run this directly from the prompt at least:

```
C:\Users\gashcrumb\Documents\GitHub\PRs\ipaas-rest\runtime\target\keycloak\keycloak-2.5.1.Final\bin\standalone.bat
```

**Comment by gashcrumb** [comment]
Lemme just try relocating my clone of your branch and give it a test, could be a weird Windows limitation with CreateProcess we're seeing here.

**Comment by gashcrumb** [comment]
Same deal.  Wonder if it's something like this -> http://stackoverflow.com/a/40648879

**Comment by jimmidyson** [comment]
@gashcrumb If you do

```
cd C:\Users\gashcrumb\Documents\GitHub\PRs\ipaas-rest\runtime\target\keycloak\keycloak-2.5.1.Final\bin\
standalone.bat
```

What happens? Or do we need to prefix with .\ or something?

**Comment by gashcrumb** [comment]
yeah, you need to do `.\standalone.bat`, doesn't work without the relative path bit.

**Comment by gashcrumb** [comment]
Yay, `mvn clean install` worked for me now...  I'll try `start-with-keycloak.bat` now...

**Comment by gashcrumb** [comment]
`start-with-keycloak.cmd`:

```
'#' is not recognized as an internal or external command,
```

use `REM` I think instead of `#` for comments?  Other than that it seems to work...

**Comment by gashcrumb** [comment]
Weird, when I `CTRL-C` it I see:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:44 min
[INFO] Finished at: 2017-02-08T16:39:21-05:00
[INFO] Final Memory: 66M/469M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.4.RELEASE:run (default-cli) on project runtime: Could not exec java: Application finished with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] Stopping all processes ...
[INFO] Stopping process: Keycloak
[INFO] Stopped process: Keycloak
``` is that expected?

**Comment by jimmidyson** [comment]
Yeah that's expected - it doesn't break anything at least ;)

**Comment by jimmidyson** [comment]
[merge]

**Pull request merged**
